namespace IAMRS.Core.Enums;

/// <summary>
/// Represents the type of alert generated by the system.
/// </summary>
public enum AlertType
{
    /// <summary>
    /// Temperature exceeds threshold.
    /// </summary>
    HighTemperature = 0,

    /// <summary>
    /// Vibration levels abnormal.
    /// </summary>
    AbnormalVibration = 1,

    /// <summary>
    /// Machine has gone offline.
    /// </summary>
    MachineOffline = 2,

    /// <summary>
    /// Pressure outside normal range.
    /// </summary>
    PressureAnomaly = 3,

    /// <summary>
    /// Predictive maintenance recommended.
    /// </summary>
    PredictiveMaintenance = 4,

    /// <summary>
    /// General threshold breach.
    /// </summary>
    ThresholdBreach = 5,

    /// <summary>
    /// Communication failure with machine.
    /// </summary>
    CommunicationFailure = 6,

    /// <summary>
    /// Sensor malfunction detected.
    /// </summary>
    SensorMalfunction = 7
}
