using IAMRS.Core.Common;
using IAMRS.Core.Enums;

namespace IAMRS.Core.Entities;

/// <summary>
/// Represents an alert generated by the monitoring system.
/// </summary>
public class Alert : BaseEntity
{
    /// <summary>
    /// Foreign key to the associated machine.
    /// </summary>
    public Guid MachineId { get; set; }

    /// <summary>
    /// Type of alert.
    /// </summary>
    public AlertType Type { get; set; }

    /// <summary>
    /// Severity level of the alert.
    /// </summary>
    public AlertSeverity Severity { get; set; }

    /// <summary>
    /// Human-readable message describing the alert.
    /// </summary>
    public string Message { get; set; } = string.Empty;

    /// <summary>
    /// Detailed description with technical information.
    /// </summary>
    public string? Details { get; set; }

    /// <summary>
    /// The value that triggered the alert (if applicable).
    /// </summary>
    public double? TriggerValue { get; set; }

    /// <summary>
    /// The threshold that was breached (if applicable).
    /// </summary>
    public double? ThresholdValue { get; set; }

    /// <summary>
    /// Whether the alert has been acknowledged by an operator.
    /// </summary>
    public bool IsAcknowledged { get; set; }

    /// <summary>
    /// Timestamp when the alert was acknowledged.
    /// </summary>
    public DateTime? AcknowledgedAt { get; set; }

    /// <summary>
    /// User ID who acknowledged the alert.
    /// </summary>
    public string? AcknowledgedBy { get; set; }

    /// <summary>
    /// Notes added when acknowledging the alert.
    /// </summary>
    public string? AcknowledgementNotes { get; set; }

    /// <summary>
    /// Whether the alert has been resolved.
    /// </summary>
    public bool IsResolved { get; set; }

    /// <summary>
    /// Timestamp when the alert was resolved.
    /// </summary>
    public DateTime? ResolvedAt { get; set; }

    /// <summary>
    /// ID of the maintenance ticket created for this alert (if any).
    /// </summary>
    public Guid? MaintenanceTicketId { get; set; }

    // Navigation properties
    /// <summary>
    /// Reference to the associated machine.
    /// </summary>
    public virtual Machine Machine { get; set; } = null!;

    /// <summary>
    /// Reference to the associated maintenance ticket.
    /// </summary>
    public virtual MaintenanceTicket? MaintenanceTicket { get; set; }
}
